### ISSUE TITLE
SSRequest class is conflicting in Objective-C runtime with a system framework

### ISSUE THREAD

**Issue by nalexn** [smartystreets/smartystreets-ios-sdk#1]
I just integrated the latest version of the SDK using Cocoapods, and in runtime Xcode prints out the following:
`objc[23641]: Class SSRequest is implemented in both /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices and /var/containers/Bundle/Application/A25C094B-453E-48DC-A4E5-6D3E9F296713/AppName.app/AppName. One of the two will be used. Which one is undefined.`

This means the SDK uses the same name for one of its classes as a class from a [system framework](https://github.com/nst/iOS-Runtime-Headers/tree/master/PrivateFrameworks/StoreServices.framework). This is a severe issue that [may lead to undefined behavior](http://stackoverflow.com/questions/30581884/class-is-implemented-in-both-one-of-the-two-will-be-used) of the app.

**Comment by oshionniemela** [comment]
Fixed by f934b82512260cc6ef5982d5977a7664864d7728
