### ISSUE TITLE
Support for Carthage is broken

### ISSUE THREAD

**Issue by heyzooi** [smartystreets/smartystreets-ios-sdk#14]
Cartfile

```
github "smartystreets/smartystreets-ios-sdk" ~> 8.4.1
```

Checkout process works fine
```
*** Checking out smartystreets-ios-sdk at "8.4.1"
```

but then the build process fails because there's no shared scheme in the Xcode project

```
*** Skipped building smartystreets-ios-sdk due to the error:
Dependency "smartystreets-ios-sdk" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/smartystreets/smartystreets-ios-sdk/issues/new
```

The latest version that I tested and worked was version `7.7.3`

**Comment by DuncanBeutler** [comment]
I'm not able to reproduce this issue. Can you share the command you're running?

**Comment by heyzooi** [comment]
Just plain `carthage update`

**Comment by DuncanBeutler** [comment]
Version 8.0.0 introduced the migration from Objective-C to Swift for our iOS SDK. As the two languages are compatible, you can still use Objective-C code but this change also saw us moving away from Carthage in favor of SPM.

**Comment by heyzooi** [comment]
Awesome, thanks for the explanation! Agreed, SPM should be the way to go from now on.
