### ISSUE TITLE
Supplying invalid characters to USAutocompleteProClient causes a fatal error. 

### ISSUE THREAD

**Issue by zlippard** [smartystreets/smartystreets-ios-sdk#19]
We noticed a crash where things like newlines, tabs and unicode characters passed in to the USAutocompleteProLookup `sendLookup()` method causes a fatal error.  For example:

```swift
let smartyStreetsAutocompleteClient = ClientBuilder(id: authId, hostname: authHostName).buildUSAutocompleteProApiClient()
var lookup = USAutocompleteProLookup()
    .withSearch(search: "123\tMain\tSt\nCity State")
var error: NSError?
_ = smartyStreetsAutocompleteClient.sendLookup(lookup: &lookup, error: &error)
```

I'm able to get around this a bit by replacing occurrence of `\n` and `\t` with a space before calling `sendLookup()`, but it seems it may be best to percent encode these characters as part of the SmartyRequest's `urlEncode()` method.

**Comment by DuncanBeutler** [comment]
Fix is deployed on 8.6.5. Thank you for raising this issue! Let us know if you have any further issues!
