### ISSUE TITLE
crash: self.suggestions  is <null> when the response is empty

### ISSUE THREAD

**Issue by prajwalsprakash** [smartystreets/smartystreets-ios-sdk#2]
While parsing **self.suggestions** is **< null >** when the response is empty,
& **crashes**. please have a check before for loop.

https://github.com/smartystreets/smartystreets-ios-sdk/blob/master/Sources/SSUSAutocompleteResult.m
Line 20:
`
if (![self.suggestions isEqual: [NSNull null]]) {
for (NSDictionary *suggestion in self.suggestions) {
}
}
`

<img width="1440" alt="screen shot 2017-07-05 at 3 57 02 pm" src="https://user-images.githubusercontent.com/13864216/27860589-e06e1142-619a-11e7-8e23-fafd39f0d3ee.png">
<img width="1135" alt="screen shot 2017-07-05 at 3 57 35 pm" src="https://user-images.githubusercontent.com/13864216/27860592-e2ad4b94-619a-11e7-93f0-b56911af4d55.png">

**Comment by oshionniemela** [comment]
I can't reproduce the bug, because of the check that already exists on [line 9](https://github.com/smartystreets/smartystreets-ios-sdk/blob/master/Sources/SSUSAutocompleteResult.m#L9). Can you provide additional details about how you arrived at this error?

**Comment by prajwalsprakash** [comment]
@oshionniemela 
Thanks for your response,
Here we go on the steps when we are using this SSUSAutocompleteAPI:
1. made a search which had **no response** in suggestions
2. where the dictionary you are parsing value as < null > for suggestions key, which got assigned as [NSNULL null] - please refer screenshot.
3. So the nil check fails/skips at [line 9](https://github.com/smartystreets/smartystreets-ios-sdk/blob/master/Sources/SSUSAutocompleteResult.m#L9)
4. later in line 20 we get a crash: **[NSNull countByEnumeratingWithState:objects:count:]:** unrecognized selector sent to instance

Screenshot: while debugging this <null> in dictionary.
<img width="1440" alt="screen shot 2017-07-07 at 3 33 24 pm" src="https://user-images.githubusercontent.com/13864216/27953686-55586846-632a-11e7-8d3a-a1ceb8f7e511.png">

Thank you,
Appreciate your support

**Comment by mdwhatcott** [comment]
> 1. made a search which had no response in suggestions

What input did you send in this case? We'd like to reproduce the situation but we are missing something.

**Comment by prajwalsprakash** [comment]
https://us-autocomplete.api.smartystreets.com/suggest?auth-id=<AUTH_ID>&auth-token=<AUTH_TOKEN>&prefix=11%20rrr

We had implemented auto-suggestion when the user types text in the search box.
Please try above query, search key entered is "11%20rrr".

![screen shot 2017-07-07 at 8 37 30 pm](https://user-images.githubusercontent.com/13864216/27963921-208b631e-6354-11e7-8d56-8d0035092538.png)

<img width="1440" alt="screen shot 2017-07-07 at 8 51 03 pm" src="https://user-images.githubusercontent.com/13864216/27964564-5974f2e2-6356-11e7-83db-3c85cf8e648d.png">

**Comment by mdwhatcott** [comment]
Thanks, that helps @prajwalsprakash
