### ISSUE TITLE
How to use swift SDK via cocoa pod

### ISSUE THREAD

**Issue by siddharthsuneel-Deserve** [smartystreets/smartystreets-ios-sdk#20]
Hi team,

I wanted to integrate SmartyStreets iOS SDK via cocoapod, when tried using `pod 'SmartystreetsSDK'` only Objective-C code got installed, whereas in sample swift code is also available.

Can you please guide me how I can have the swift version of SmartyStreets iOS SDK?

**Comment by DuncanBeutler** [comment]
As of version 8.0.0 we have discontinued support for cocoapods. The swift code can be pulled down using Swift Package Manager.
