### ISSUE TITLE
Build error on M1 Mac

### ISSUE THREAD

**Issue by jeffdgr8** [smartystreets/smartystreets-ios-sdk#26]
Building an iOS app with the SmartyStreets SDK on an M1 Mac with Xcode 13 results in this build error:

> Could not find module 'SmartyStreets' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /.../Build/Products/Debug-iphonesimulator/SmartyStreets.swiftmodule

**Comment by jeffdgr8** [comment]
I was able to resolve this by removing under the **Excluded Architectures** project setting the **Any iOS Simulator** - **arm64** key/values. This was required by another legacy .a library to compile, which I had to remove. The reason the SmartyStreets SDK seems to have this issue, where other libraries didn't, is because of Swift Package Manager (other dependencies are CocoaPods).

**Comment by jcrob2** [comment]
Hi @jeffdgr8. We're glad you figured it out!
