### ISSUE TITLE
Please make USStreetCandidate & USStreetAnalysis properties public due to error: inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by reveelapp** [smartystreets/smartystreets-ios-sdk#27]
I am converting a working version that was using Cocoapods into SPM (Smarty ver: 8.9.1). I am having trouble accessing some properties from a public class, since Xcode is complaining they are not accessible. I'd prefer not to clone and make a local copy with SPM (since locked) - if you all don't mind updating to make them public in 'USStreetCandidate' & 'USStreetAnalysis'. 

**_... something like this for 'USStreetCandidate':_**
`public var status:String?`
`public var reason:String?`
`public var inputId:String? // using this`
`public var inputIndex:Int? // using this`
 `public var objcInputIndex:NSNumber? {
        get {
            return inputIndex as NSNumber?
        }
    } // already public`
`public var candidateIndex:Int? // using this`

**_... also like this for 'USStreetAnalysis':_**
`public var dpvMatchCode:String? // using this`
`public var dpvFootnotes:String? // using this`
`public var cmra:String? // using this`
`public var vacant:String? // using this`
`public var noStat:String?`
 `public var active:String? // using this`
 `public var footnotes:String? // using this`
 `public var lacsLinkCode:String? // using this`
 `public var lacsLinkIndicator:String? // using this`
 `public var isSuiteLinkMatch:Bool? // using this`
 `public var enhancedMatch:String?`

**Thank you in advance!**

**Comment by DuncanBeutler** [comment]
Updates to make the fields public are on version 8.10.11. Thanks for catching this.

**Comment by reveelapp** [comment]
Cool. I did not see the 8.10.1.1 release on github though I was able to pull it specifically with SPM. Those properties now work (after updating some new & proper optionals), thanks!
