### ISSUE TITLE
Restructure code to play nicely with asynchronous NSURLSession.

### ISSUE THREAD

**Issue by oshionniemela** [smartystreets/smartystreets-ios-sdk#3]
We wrote this code by translating from our other SDK's we have written which all use synchronous network I/O. We need this code to be restructured such that it plays nicely in iOS environments.
https://github.com/smartystreets/smartystreets-ios-sdk/blob/master/Sources/SSHttpSender.m#L59

**Comment by MouaYing** [comment]
This has been fixed in version 7.3.3.
